#!/bin/bash
################################################################################
# NAME:
#     scriptTemplate                                 
#                                                              
# DESCRIPTION:                                                 
#     Use this template as the beginning of a new program.     
#         $ cp scriptTemplate newProgram                       
#     Place a short description of the script here.            
#                                                              
# CHANGE HISTORY:                                              
#     05/17/2024 - Jason Sparks                                
#     Original code. This is a template for creating new Bash  
#     shell scripts.                                           
#                                                              
#     Add new history entries as needed.                       
#                                                              
#                                                              
################################################################################
#                                                              
# Copyright (C) 2024 Jason Sparks                        
# hijasonsparks@gmail.com                                      
#                                                              
# This program is free software; you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by 
# the Free Software Foundation; either version 3 of the License, or 
# (at your option) any later version.                                               
#                                                              
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU General Public License for more details.                                                     
#                                                              
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#                                                              
################################################################################
#                                                                               
#                                   FUNCTIONS                                   
#                                                                               
################################################################################

Help() {
	# Display help facility.
	echo "Usage: $0 [options]"
	echo "    Add description of the script functions here."
	echo
	echo "    Options:"
	echo "        -h    Print this Help."
	echo "        -l    Print the GPL license notification."
	echo "        -V    Print software version and exit."
	echo
}

PrintLicense() {
	# Display GPL info. 
	echo ""
	echo "Copyright (C) 2024 Jason Sparks"
	echo "<hijasonsparks@gmail.com>"
	echo ""
	echo "This program is free software: you can redistribute it and/or modify"
	echo "it under the terms of the GNU General Public License as published by"
	echo "the Free Software Foundation, either version 3 of the License, or"
	echo "(at your option) any later version."
	echo ""
	echo "This program is distributed in the hope that it will be useful,"
	echo "but WITHOUT ANY WARRANTY; without even the implied warranty of"
	echo "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the"
	echo "GNU General Public License for more details."
	echo ""
	echo "You should have received a copy of the GNU General Public License"
	echo "along with this program.  If not, see <https://www.gnu.org/licenses/>."
	echo ""
}

PrintVersion(){
	echo "Version $version"
}

IsRoot() {
	# Check if the script was ran as root using the "Effective User ID".
	if [[ $EUID -ne 0 ]]; then
		echo "ERROR: This script must be ran as root"
		exit 1
	fi
}


################################################################################
#                                                                               
#                                 MAIN PROGRAM                                  
#                                                                               
################################################################################

# If the script should only be ran as root uncomment the below line 
#IsRoot

# Initialize variables
version="1.0.0"
Msg="scriptTemplate"
OPTSTRING=":hlV"

# Process the input options. Add options as needed. 
# Get the options 
while getopts ${OPTSTRING} option; do 
	case $option in 
		h) # Display Help
			Help
			exit
			;;
		l) # Display the GPL license
			PrintLicense
			exit
			;;
		V) # Display the version
			PrintVersion
			exit
			;;
		\?) # Ivalid option 
			echo "ERROR: Invalid option"
			Help
			exit 2
			;;
	esac
done

echo "$Msg"
